@Url=http://localhost:9546

POST {{Url}}
Content-Type: application/json

{
    "method": "net_version",
    "jsonrpc": "2.0",
    "id":1
}
###

POST {{Url}}
Content-Type: application/json

{
    "method": "eth_chainId",
    "jsonrpc": "2.0",
    "id":1
}
###

POST {{Url}}
Content-Type: application/json

{
	"params":
	[{
		"from":"0x5561035012fcb5d4af49a200412de5545087d3d6",
		"value":"0x29a2241af62c0000",
		"gasPrice":"0x4a817c800",
		"data":"0x",
		"to":"0x8b029e7733e1eff582d17ec9e9f9a45f745bcb05"
	}],
	"id":9661311584379,
	"jsonrpc":"2.0",
	"method":"eth_estimateGas"	
}
###

POST {{Url}}
Content-Type: application/json

{
	"params": ["0x5561035012fcb5d4af49a200412de5545087d3d6", "0x29a2241af62c0000"],
	"id":9661311584379,
	"jsonrpc":"2.0",
	"method":"eth_getCode"	
}
###

POST {{Url}}
Content-Type: application/json

{
	
	"params": ["0xf86f81ab8504a817c80082520894e82083c8434b4395de90e58e7c0afab10a2d2aa4884563918244f4000080820d07a0fd42c57f8a6fc72a8d704737037ef0e8fc9b7e6351a5454fd25e41f6035eda92a03ca093f548d1198498cfd7f57122f98badb29dba29d7be06330821ae0552e5d0"],
	"id":9661311584379,
	"jsonrpc":"2.0",
	"method":"eth_sendRawTransaction"	
}
###

POST {{Url}}
Content-Type: application/json

{
	
	"params": ["0x"],
	"id":9661311584379,
	"jsonrpc":"2.0",
	"method":"eth_sendRawTransaction"	
}
###

POST {{Url}}
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByHash",
    "params": [
        "0xe76d777791f48b5995d20789183514f4aa8bbf09e357383e9a44fae025c6c50a",
        true
    ],
    "id": 0
}
###

POST {{Url}}
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getBlockByNumber",
  "params": [
    "0x01",
    true
  ]
}
###

POST {{Url}}
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionCount",
  "params": [
    "0x3f349bBaFEc1551819B8be1EfEA2fC46cA749aA1",
    "latest"
  ]
}
###

POST {{Url}}
Content-Type: application/json

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_blockNumber"
}
###